In [22]:
import pandas as pd 

In [23]:
df = pd.read_csv("vgsalesGlobale.csv")

In [24]:
total_global_sales = df['Global_Sales'].sum()
print("Total Global Sales:", total_global_sales)


Total Global Sales: 8920.44


In [25]:
game_with_highest_sales = df.loc[df['Global_Sales'].idxmax()]
print("Game with the highest global sales:", game_with_highest_sales['Name'])


Game with the highest global sales: Wii Sports


In [26]:
average_sales_by_region = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average Sales by Region:")
print(average_sales_by_region)


Average Sales by Region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [27]:
genre_sales_by_region = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre_na = genre_sales_by_region['NA_Sales'].idxmax()
print(f"Most popular genre in North America based on sales: {most_popular_genre_na}")


Most popular genre in North America based on sales: Action


In [28]:
last_10_rows = df.tail(10)
print("Last 10 rows of the dataset:")
print(last_10_rows)


Last 10 rows of the dataset:
        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01

In [29]:
top_3_platforms = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(3)
print("Top 3 gaming platforms with highest global sales:")
print(top_3_platforms)


Top 3 gaming platforms with highest global sales:
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [30]:
total_sales = df['Global_Sales'].sum()
genre_sales = df.groupby('Genre')['Global_Sales'].sum()
genre_market_share = (genre_sales / total_sales) * 100
print("Market share (percentage of global sales) for each genre:")
print(genre_market_share)


Market share (percentage of global sales) for each genre:
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [31]:
correlation_na_eu = df['NA_Sales'].corr(df['EU_Sales'])
print(f"Correlation coefficient between NA_Sales and EU_Sales: {correlation_na_eu}")


Correlation coefficient between NA_Sales and EU_Sales: 0.767726748370263


In [32]:
# Creating an English-Spanish dictionary
dictionary = {
    "hello": "hola",
    "goodbye": "adiós",
    "book": "libro"
}

# Loop to allow multiple lookups
while True:
    # Asking the user to input an English word
    word = input("Enter an English word to translate to Spanish (or 'exit' to quit): ").lower()
    
    # Exit condition
    if word == 'exit':
        print("Goodbye!")
        break
    
    # Check if the word exists in the dictionary
    if word in dictionary:
        print(f"The Spanish translation of '{word}' is '{dictionary[word]}'.")
    else:
        print(f"Sorry, the translation for '{word}' is not available.")


The Spanish translation of 'hello' is 'hola'.
The Spanish translation of 'hello' is 'hola'.
Goodbye!


In [36]:
import re

def classify_emails(emails):
    # Keywords for each category
    important_keywords = ['urgent', 'important']
    promotions_keywords = ['offer', 'deal', 'sale', 'discount']
    spam_keywords = ['free', 'win', 'cash prize', 'lottery']

    # Categorized email lists
    important_emails = []
    promotions_emails = []
    spam_emails = []

    # Loop through each email and classify
    for email in emails:
        email_lower = email.lower()

        # Check for important keywords
        if any(keyword in email_lower for keyword in important_keywords):
            important_emails.append(email)

        # Check for promotions keywords
        if any(keyword in email_lower for keyword in promotions_keywords):
            promotions_emails.append(email)

        # Check for spam keywords
        if any(keyword in email_lower for keyword in spam_keywords):
            spam_emails.append(email)

    # Return categorized lists
    return important_emails, promotions_emails, spam_emails

# Example usage
emails = [
    "Urgent action required: Your account has been compromised.",
    "Congratulations! You've won a free cash prize!",
    "Limited time offer: 50% off on all items. Buy now!",
    "Important: Your payment is due tomorrow.",
    "Don't miss out! Win a lottery prize today!",
    "Reminder: Project deadline is in 2 days.",
    "Exclusive discount just for you! Sale ends soon."
]

important, promotions, spam = classify_emails(emails)


print("Important Emails:")
print(important)
print("\nPromotions Emails:")
print(promotions)
print("\nSpam Emails:")
print(spam)


Important Emails:
['Urgent action required: Your account has been compromised.', 'Important: Your payment is due tomorrow.']

Promotions Emails:
['Limited time offer: 50% off on all items. Buy now!', 'Exclusive discount just for you! Sale ends soon.']

Spam Emails:
["Congratulations! You've won a free cash prize!", "Don't miss out! Win a lottery prize today!"]


In [34]:
import numpy as np

# Create two NumPy arrays of the same shape
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Element-wise addition
sum_array = array1 + array2
print("Element-wise addition:")
print(sum_array)

# Element-wise product
product_array = array1 * array2
print("\nElement-wise product:")
print(product_array)


Element-wise addition:
[ 6  8 10 12]

Element-wise product:
[ 5 12 21 32]


In [35]:
import numpy as np


array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

array_2d = array_1d.reshape(3, 4)
print("Reshaped 2D array (3, 4):")
print(array_2d)

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

horizontal_concat = np.concatenate((array1, array2), axis=0)
print("\nHorizontal concatenation:")
print(horizontal_concat)

vertical_concat = np.concatenate((array1.reshape(-1, 1), array2.reshape(-1, 1)), axis=1)
print("\nVertical concatenation:")
print(vertical_concat)


Reshaped 2D array (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Horizontal concatenation:
[1 2 3 4 5 6]

Vertical concatenation:
[[1 4]
 [2 5]
 [3 6]]


In [37]:
my_list = [1, 2, 3, 4, 5]
reversed_list = my_list[::-1]
print(reversed_list)


[5, 4, 3, 2, 1]


In [38]:
# Initialize an empty list for the shopping cart
shopping_cart = []

# Display a welcome message and available products
print("Welcome to the online store!")
print("Available products:")
print("1. AI Response Simulator")
print("2. Investment Decision Tool")
print("3. Data Analytics Suite")
print("To quit, type 'q'.")

# Start a loop to interact with the user
while True:
    # Prompt the user to enter the number corresponding to the product they want to add
    choice = input("Enter the number of the product you want to add to the cart (or 'q' to quit): ")

    # Check if the user wants to quit the program
    if choice.lower() == 'q':
        break

    # Validate the input (make sure it's an integer within the valid range)
    if choice.isdigit():
        choice = int(choice)
        if 1 <= choice <= 3:
            # Add the selected product to the shopping cart
            if choice == 1:
                shopping_cart.append("AI Response Simulator")
                print("AI Response Simulator added to your shopping cart.")
            elif choice == 2:
                shopping_cart.append("Investment Decision Tool")
                print("Investment Decision Tool added to your shopping cart.")
            elif choice == 3:
                shopping_cart.append("Data Analytics Suite")
                print("Data Analytics Suite added to your shopping cart.")
        else:
            print("Invalid choice! Please select a number between 1 and 3.")
    else:
        print("Invalid input! Please enter a number between 1 and 3 or 'q' to quit.")

# Display the contents of the shopping cart after the loop ends
print("\nYour shopping cart contains:")
for item in shopping_cart:
    print("- " + item)

# Display a goodbye message
print("\nThank you for shopping with us! Goodbye!")


Welcome to the online store!
Available products:
1. AI Response Simulator
2. Investment Decision Tool
3. Data Analytics Suite
To quit, type 'q'.
Investment Decision Tool added to your shopping cart.
Data Analytics Suite added to your shopping cart.
Invalid choice! Please select a number between 1 and 3.

Your shopping cart contains:
- Investment Decision Tool
- Data Analytics Suite

Thank you for shopping with us! Goodbye!
